# Generated by Django 4.2.27 on 2026-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='The role of the message sender (user, assistant, or system)', max_length=20)),
                ('content', models.TextField(help_text='The actual message content')),
                ('model_name', models.CharField(help_text="The AI model used for this conversation (e.g., 'openai/gpt-4')", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this message was created')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Optional session identifier to group related messages', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
